# Generated by Django 4.1 on 2022-08-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
